### ISSUE TITLE
Lower MySQL version requirements.

### ISSUE THREAD

**Issue by Beanow** [Mokuji/mokuji#35]
As of now the requirement is 5.0.3+ because of ONE field.
In the table `#__cms_pages` is a field `keywords varchar(2000)`
Varchar can only be greater than 255 since 5.0.3. If this is removed any 5.x MySQL database should be compatible.

Also, should this be updated be sure to update the requirements check for the installing process. (`update/Sections.php`).

**Comment by Avaq** [comment]
This was already changed since `com:cms` version 2.0, the problem was that the update script responsible for the change had a bug. This bug, however, was fixed by Bart in [1efd594429ce4cb86e9016c4c7758d999b40cbb6](https://github.com/Tuxion/tuxion.cms/commit/1efd594429ce4cb86e9016c4c7758d999b40cbb6).
