### ISSUE TITLE
Email validation fails when not given a domain.

### ISSUE THREAD

**Issue by Avaq** [Mokuji/mokuji#57]
This means that perfectly valid email addresses such as `avaq@127.0.0.1` or `avaq@localhost` invalidate, preventing people from even installing Mokuji with one such address.

**Comment by Avaq** [comment]
This appears to be a problem with PHP's filter_var function.

**Comment by Beanow** [comment]
Using full domain names is safer for certain use cases. For example when the e-mail is supposed to be displayed publicly, `user@localhost` would not work well. If the website moves to another host, the addresses may become invalid, etc. If you have a need for this it would need to be an 'opt-in' exception to not break current validation assumptions.

Until then, closing this issue because I haven't heard from any users considering this to be a significant problem.

**Comment by Avaq** [comment]
Alright, cool. Didn't think of the security implications. :+1:
